# Generated by Django 4.2.6 on 2023-11-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.BigIntegerField()),
                ('measure_choice', models.CharField(choices=[('mg', 'Miligramas'), ('g', 'Gramas'), ('kg', 'Quilogramas'), ('ml', 'Mililitros'), ('L', 'Litros')], default='mg', max_length=3)),
                ('measure', models.IntegerField()),
                ('amout', models.BigIntegerField()),
                ('extends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='models.product')),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='models.product')),
            ],
        ),
    ]
