# Generated by Django 5.0.6 on 2024-05-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('choosen_measure', models.CharField(choices=[('mg', 'Miligramas'), ('g', 'Gramas'), ('kg', 'Quilogramas'), ('ml', 'Mililitros'), ('L', 'Litros')], default='mg', max_length=3)),
                ('measure', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Na fila'), (1, 'Pendente'), (2, 'Pronto'), (3, 'Completa')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity', models.DateTimeField()),
                ('amount', models.SmallIntegerField()),
                ('lot_number', models.BigIntegerField(null=True)),
                ('due', models.BooleanField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.product')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('id_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.purchase')),
                ('id_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_phone', models.CharField(max_length=11)),
                ('secondary_phone', models.CharField(max_length=11, null=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('town', models.CharField(max_length=300)),
                ('neighborhood', models.CharField(max_length=300)),
                ('public_place', models.CharField(max_length=200)),
                ('complement', models.CharField(max_length=500)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.supplier')),
            ],
        ),
    ]
