# Generated by Django 4.2.6 on 2023-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amout',
            new_name='amount',
        ),
    ]
