# Generated by Django 5.0.4 on 2024-05-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Na fila'), (1, 'Pendente'), (2, 'Pronto'), (3, 'Completa')], default=0),
        ),
    ]
