# Generated by Django 5.0.4 on 2024-05-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_compra_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='id_Produto',
            new_name='id_produto',
        ),
    ]
