# Generated by Django 5.0.3 on 2024-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_amount_product_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='previous_shops',
            field=models.ManyToManyField(null=True, to='models.sale'),
        ),
    ]
