# Generated by Django 5.0.3 on 2024-04-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_customer_previous_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='previous_shops',
        ),
    ]
