# Generated by Django 5.0.4 on 2024-04-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_customer_previous_shops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='batch',
            new_name='Stock',
        ),
    ]
